### PR TITLE
TLS intolerance scanning

### PR DESCRIPTION
**Pull request by tomato42**
just a quick and dirty example to show how we can test for TLS version tolerance for any version

the script is run as
```
./cscan.sh hostname port
```

part of work towards #108

### CODE REVIEW

**Comment by tomato42** [comment]
@jvehent: it took me some time, but I think I have something good enough

the most important part is the `cscan.py` file, there, in `scan_TLS_intolerancies()`, you can see how we can take a "config" (a description of how to create a Client Hello of a specific library/application), inspect them and decide if the server is intolerant to some client behaviour or not 

I'm know that the merge request is rather big, but I wanted to check if the architecture works for more complex scenarios so if you could take a look at `HelloConfig` and `Firefox_42` in `cscan/config.py` and then at `no_sni()` and `set_hello_version()` in `cscan.py`, that should give you good overall feel for how it works and if it's something you'd like

once I have your reply I'll start reworking it so that it starts with a patch for a simplest working example and builds from there

**Comment by tomato42** [comment]
with the new patch, the script can now be run like this:
```
./cscan.sh host-or-IP port hostname-for-sni
```
to use different hostname for the TCP connection and different for the server name indication extension

**Comment by jvehent** [comment]
I need to take some time to play with your code, but workload is high nowadays so it might take me a while to get to it.

**Comment by tomato42** [comment]
one more command line parameters change, now you start it like this:

```
./cscan.sh example.com
```

or the full syntax:
```
./cscan.sh 127.0.0.1:443 example.com
```

where IP is the address used for connecting and `example.com` is the SNI hostname

**Comment by jvehent** [comment]
I started looking. The code runs fine, although it's not obvious what it does. a `-debug` option that prints detailed tests would be nice, similar to cipherscan's `-v`.

I need to spend more time in your code to understand the configuration logic you describe. Am I correct to understand that there is two part: a "framework" for scanning and "tests" that perform specific intolerance scans?

**Comment by tomato42** [comment]
> The code runs fine, although it's not obvious what it does. a -debug option that prints detailed tests would be nice, similar to cipherscan's -v

some debug may be neat too, but I'll probably focus more on putting the code under unit tests, much more robust than having debugging and hoping it runs correctly :)

as for outputs, for now it can do only the json output, I need to create a human readable version of output still. That will include more detailed information about specific probes and results from them (try changing `False` to `True` in the code below for a unrefined taste.

```
    if False:                                                                    
        for desc, ret in results.items():                                       
            print(verbose_inspector(desc, ret))
```

I also want to be able to easily run a single probe against a given server to see its results

> I need to spend more time in your code to understand the configuration logic you describe. 

sure, feel free to ask, the code definitely can accommodate a wee bit more comments, but not much more :wink: 

> Am I correct to understand that there is two part: a "framework" for scanning and "tests" that perform specific intolerance scans?

well, I'm trying to make the code modular and separated into logical parts

but you can definitely separate the stuff in `scan_TLS_intolerancies()` as a set of tests compared to the rest of code being more framework-like

the newest patches added a new test (though I'm not exactly happy how it turned out to be) that is closer to "tests" tests

What I was thinking, is that nobody in their right mind would deploy a web server to which _nothing_ can connect to. So the first set of probes (the `configs` in `scan_TLS_intolerancies()`) are there to see if the server can be connected to at all, especially with some currently, or in the past, popular browsers. Once the scanner knows that the server actually does implement SSL or TLS, it can zoom in on specific intolerancies/incompatibilites (and that's the new addition).

**Comment by tomato42** [comment]
*now* it's a good scanner! :smile: 

so, I've updated it to not run every single probe to the server, but only as many as are necessary to show that a specific intolerance is not present, as soon as a configuration matching intolerance test connects, it does not use subsequent probes, in effect performing a much quicker scan

the bisect on sizes is still a bit slow, but that's because the tlslite-ng `Codec` is slow and is used in comparing extensions

**Comment by tomato42** [comment]
human-readable output by default with json output when specified (and support for `-h`/`--help`)

**Comment by tomato42** [comment]
I've reworked the patches into three logical parts - logic of the scanner, additional version and extensions probes, size intolerance.

old branch is here https://github.com/tomato42/cipherscan/tree/cscan-3

when can I expect review? Specific suggestions to make it quicker welcome :smile:

**Comment by tomato42** [comment]
@jvehent I've fixed the human-readable output from cscan when run through cipherscan (it's now included).

**Comment by jvehent** [comment]
@tomato42: I sort of would like to reopen this and merge it. Any update?

**Comment by tomato42** [comment]
I need to rework it, will try to do this this week.

**Pull request closed without merging**
