### PR TITLE
Update cipherscan

### PR DESCRIPTION
**Pull request by sunshuzhou**
Simple add `continue` in the `read line` loop.

### CODE REVIEW

**Comment by tomato42** [comment]
nice catch, could you also add a `continue` to the if just below those two ones?

**Comment by sunshuzhou** [comment]
Sure.

**Comment by tomato42** [comment]
no, in line 497 actually not, the `Signature Algorithm` is reported twice (as it is defined twice in certificate), we are interested in the second instance if they are different

**Comment by tomato42** [comment]
Thanks!

**Pull request merged**
